config/routes.rb
Rails.application.routes.draw do

  resources :books do
    resources :comments
  end
  resources :publishes
  resources :categories

  root 'books#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users, :controllers => { passwords: 'passwords' }

end

app/models/book.rb
# book model
class Book < ActiveRecord::Base
  belongs_to :category
  belongs_to :publish
  has_many :comments
  validates :title, presence: true,
                    length: { maximum: 500 }
  validates :cost, presence: true,
                   numericality: { greater_than_or_equal_to: 1 }
  validates :sale, presence: true,
                   numericality: { greater_than_or_equal_to: 0, is_less_than_or_equal_to: 0.75 }
  validates :weight, presence: true,
                   numericality: { greater_than_or_equal_to: 10 }
  validates :photo, presence: true
  validates :content, presence: true
  validates :category_id, presence: true,
                          numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :publish_id,  presence: true,
                          numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :pages, presence: true,
                    numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  PER_PAGE = 12

  def self.book_list(page)
    @book = Book.paginate(page: page, per_page: PER_PAGE)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.book_list(params[:page])
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @books = @book.category.books.where.not(id: @book.to_param).limit(8)
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:category_id, :title, :author, :publish_id, :cost, :sale, :photo, :content, :weight, :size, :pages, :date)
    end
end

app/helpers/books_helper.rb
module BooksHelper
  def price book
    (book.cost - book.cost * book.sale).round(2)
  end
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :publish_id %><br>
    <%= f.number_field :publish_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :sale %><br>
    <%= f.text_field :sale %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :pages %><br>
    <%= f.text_field :pages %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_signle_book.html.erb
<div class="col-md-3 col-ms-6" >
  <div class="single-product" >
    <div class="product-f-image">
      <%= image_tag book.photo %>
      <div class="product-hover">
        <a href="#" class="add-to-cart-link">
          <i class="fa fa-shopping-cart"></i> Add to cart
        </a>
        <a href=<%= book_path(book) %> class="view-details-link">
          <i class="fa fa-link"></i> See details
        </a>
      </div>
    </div>

    <div class="abc" data-toggle="tooltip" data-placement="top" title = "<%= book.title %>">
      <h2>
        <% if book.title.size > 21 %>
        <a href=<%= book_path(book) %>> <%= book.title[0..20]  %> ...</a>
        <% else %>
        <a href=<%= book_path(book) %>> <%= book.title %></a>
        <% end %>
      </h2>
    </div>

    <div class="product-carousel-price">
      <ins>$<%= price(book) %></ins> <del>$<%= book.cost %></del>
    </div>

  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
  });
</script>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="single-product-area">
  <div class="container">
    <div class="row">
      <% if !@books.nil? %>
        <% @books.each do |book| %>
          <%= render partial: "signle_book", locals: { book: book } %>
        <% end %>
      <% end %>
    </div>
    <div class="digg_pagination text-center" >
      <%= will_paginate @books %>
    </div>
  </div>
</div>
<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="single-product-area">
  <div class="zigzag-bottom"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="single-sidebar">
          <h2 class="sidebar-title">RELATED PRODUCTS</h2>
          <% unless @book.nil? %>
            <% @books.each do |book| %>
            <div class="thubmnail-recent">
              <img src="<%= book.photo %>" class="recent-thumb" alt="">
              <h2><a href=<%= book_path(book) %>> <%= book.title %> </a></h2>
              <div class="product-sidebar-price">
                <ins>$<%= price(book) %></ins> <del>$<%= book.cost %></del>
              </div>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="col-md-8">
        <div class="product-content-right">
          <div class="product-breadcroumb">
            <a href="#">Home</a>
            <a href="<%= category_path(@book.category) %>"><%=@book.category.name %></a>
            <a href="<%= book_path(@book) %>""> <%= @book.title %> </a>
          </div>

          <div class="row">
            <div class="col-sm-6">
              <div class="product-images">
                <div class="product-main-img">
                  <img id="zoom_book" src="<%= @book.photo %>" data-zoom-image="<%= @book.photo %>"/>
                </div>
              </div>
            </div>

            <div class="col-sm-6">
              <div >
                <h2 class="product-name"><%= @book.title %></h2>
                <div class="product-inner-price">
                  <ins>$<%= price(@book) %></ins> <del>$<%= @book.cost %></del>
                </div>

                <form action="" class="cart">
                  <div class="quantity">
                    <input type="number" size="4" class="input-text qty text" title="Qty" value="1" name="quantity" min="1" step="1">
                  </div>
                  <button class="add_to_cart_button" type="submit">Add to cart</button>
                </form>

                <div class="product-inner-category">
                  <p>Category: <a href=""> <%= @book.category.name%> </a></p>
                </div>

                <div role="tabpanel">
                  <ul class="product-tab" role="tablist">
                    <li role="presentation" class="active"><a href="#desciption" aria-controls="home" role="tab" data-toggle="tab">Description</a></li>
                    <li role="presentation"><a href="#comment" aria-controls="profile" role="tab" data-toggle="tab">Reviews</a></li>
                  </ul>
                  <div class="tab-content">
                    <div role="tabpanel" class="tab-pane fade in active" id="desciption">
                      <h2> Introduce Book </h2>
                      <p> <%= @book.content %> </p>
                    </div>
                    <div role="tabpanel" class="tab-pane fade" id="comment">
                      <h2>Reviews</h2>
                      <div class="submit-review">
                        <div class="rating-chooser">
                          <p>Your rating</p>
                          <div class="rating-wrap-post">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                          </div>
                        </div>
                        <div id="commented">
                          <%= render partial: @book.comments.includes(:user) %>
                        </div>
                        <div>
                          <% if current_user.nil? %>
                            <a data-toggle="modal" href="#login_form"><i class="fa fa-user"></i> Login for comment</a>
                          <% else %>
                            <%= render 'comments/form' %>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            </div>

            <div class="related-products-wrapper">
              <h2 class="related-products-title">Details Book</h2>
              <table class="table table-bordered table-detail table-striped">
                <tbody>
                  <tr>
                    <td> Author </td>
                    <td> <%= @book.author %> </td>
                  </tr>
                  <tr>
                    <td> Publisher </td>
                    <td> <%= @book.publish.name %> </td>
                  </tr>
                  <tr>
                    <td> Shipping Weight </td>
                    <td> <%= @book.weight %> gram </td>
                  </tr>
                  <tr>
                    <td> Product Dimensions </td>
                    <td> <%= @book.size %> cm </td>
                  </tr>
                  <tr>
                    <td> Paperback </td>
                    <td> <%= @book.pages %> pages </td>
                  </tr>
                  <tr>
                    <td> Date publish </td>
                    <td> <%= @book.date %> </td>
                  </tr>
                </tbody>
              </table>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    $("#zoom_book").elevateZoom({
      zoomWindowFadeIn: 500,
      zoomWindowFadeOut: 500,
      lensFadeIn: 500,
      lensFadeOut: 500
    });
  </script>