config/routes.rb
Rails.application.routes.draw do

  resources :books do
    resources :comments
  end
  resources :publishes
  resources :categories

  root 'books#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users, :controllers => { passwords: 'passwords' }

end

app/views/layouts/user_session/_forgot_password.html.erb
<div role="tabpanel" class="tab-pane text-center" id="forget_password">
  &nbsp;&nbsp;
  <span id="reset_fail" class="response_error" style="display: none;"></span>
  <div class="clearfix"></div>
  <%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>

  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon"><i class="fa fa-user"></i></div>
      <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Email" %>
    </div>
    <span class="help-block has-error" data-error='0' id="femail-error"></span>
  </div>
  <%= f.submit "Forget Password", class: "btn btn-primary btn-block" %>
  <div class="clearfix"></div>
  <div class="login-modal-footer">
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6">
        <i class="fa fa-lock"></i>
        <a href="javascript:;" class="signin-tab"> Sign In </a>

      </div>

      <div class="col-xs-6 col-sm-6 col-md-6">
        <i class="fa fa-check"></i>
        <a href="javascript:;" class="signup-tab"> Sign Up </a>
      </div>

      <div class="col-md-12">
        <i class="fa fa-lock"></i>
        <%= link_to "Didn't receive confirmation email?", new_user_confirmation_path %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/user_session/_sign_in.html.erb
<div role="tabpanel" class="tab-pane active text-center" id="home">
  &nbsp;&nbsp;
  <span id="login_fail" class="response_error" style="display: none;">Loggin failed, please try again.</span>

  <div class="clearfix"></div>
  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon"><i class="fa fa-user"></i></div>
      <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Email" %>
    </div>
    <span class="help-block has-error" id="email-error"></span>
  </div>
  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon"><i class="fa fa-lock"></i></div>
      <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Password" %>
    </div>
    <span class="help-block has-error" id="password-error"></span>
  </div>
  <%= f.submit "Log in", class: "btn btn-primary btn-block" %>
  <div class="clearfix"></div>
  <div class="login-modal-footer">
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6">
        <i class="fa fa-lock"></i>
        <a href="javascript:;" class="forgetpass-tab"> Forgot password? </a>

      </div>

      <div class="col-xs-6 col-sm-6 col-md-6">
        <i class="fa fa-check"></i>
        <a href="javascript:;" class="signup-tab"> Sign In </a>
      </div>
      <div class="col-md-12">
        <i class="fa fa-lock"></i>
        <%= link_to "Didn't receive confirmation email?", new_user_confirmation_path %>
      </div>

    </div>
  </div>
  <% end %>
</div>

app/views/layouts/user_session/_sign_up.html.erb
<div role="tabpanel" class="tab-pane" id="profile">
  &nbsp;&nbsp;
  <span id="registration_fail" class="response_error" style="display: none;">Registration failed, please try again.</span>
  <div class="clearfix"></div>
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon"><i class="fa fa-user"></i></div>
      <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Email" %>
    </div>
    <span class="help-block has-error" data-error='0' id="username-error"></span>
  </div>
  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon"><i class="fa fa-at"></i></div>
      <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Password" %>
    </div>
    <span class="help-block has-error" data-error='0' id="remail-error"></span>
  </div>

  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon"><i class="fa fa-at"></i></div>
      <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: "Confirm Password" %>
    </div>
    <span class="help-block has-error" data-error='0' id="remail-error"></span>
  </div>
  <%= f.submit "Register", class: "btn btn-primary btn-block" %>
  <div class="clearfix"></div>
  <div class="login-modal-footer">
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6">
        <i class="fa fa-lock"></i>
        <a href="javascript:;" class="forgetpass-tab"> Forgot password? </a>

      </div>

      <div class="col-xs-6 col-sm-6 col-md-6">
        <i class="fa fa-check"></i>
        <a href="javascript:;" class="signin-tab"> Sign Up </a>
      </div>

      <div class="col-md-12">
        <i class="fa fa-lock"></i>
        <%= link_to "Didn't receive confirmation instructions?", new_user_confirmation_path %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/user_session/_user_authenticate.html.erb
<!-- -Login Modal -->
<div class="modal fade" id="login_form" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4><span class="glyphicon glyphicon-lock"></span> User Authenticate</h4>
      </div>
      <div class="modal-body">
        <div class="text-center">
          <div role="tabpanel" class="login-tab">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
              <li role="presentation" class="active"><a id="signin-taba" href="#home" aria-controls="home" role="tab" data-toggle="tab">Sign In</a></li>
              <li role="presentation"><a id="signup-taba" href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Sign Up</a></li>
              <li role="presentation"><a id="forgetpass-taba" href="#forget_password" aria-controls="forget_password" role="tab" data-toggle="tab">Forget Password</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
              <%= render 'layouts/user_session/sign_in' %>
              <%= render 'layouts/user_session/sign_up' %>
              <%= render 'layouts/user_session/forgot_password' %>
            </div>
          </div>

        </div>
      </div>

    </div>
  </div>
</div>
<!-- - Login Model Ends Here -->

<!-- Message after authenticate -->

<% if flash[:notice] %>
<%= render 'layouts/modal_message/notice_message' %>
<% elsif devise_error_messages! != "" %>
<%= render 'layouts/modal_message/error_message'%>
<% elsif flash[:alert] %>
<%= render 'layouts/modal_message/alert_message' %>
<% end %>

<script>
  $(document).ready(function(){
    $(document).on('click','.signup-tab',function(e){
      e.preventDefault();
      $('#signup-taba').tab('show');
    });

    $(document).on('click','.signin-tab',function(e){
      e.preventDefault();
      $('#signin-taba').tab('show');
    });

    $(document).on('click','.forgetpass-tab',function(e){
      e.preventDefault();
      $('#forgetpass-taba').tab('show');
    });

    $(window).load(function(){
      $('#myModal').modal('show');
    });

  });
</script>